version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      PGUSER: postgres
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 3s
      retries: 30
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - db
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:3000/healthy"]
