default: &default
  adapter: postgresql
  encoding: unicode
  prepared_statements: false
  pool: 5

development:
  <<: *default
  database: hometime_dev
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>

test:
  <<: *default
  database: hometime_test
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
